# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GC TOOLS
                                 A QGIS plugin
 MMS Data Plugin for Qgis with all kind of info
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-14
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Mateus Melo Siqueira/Remis Balaniuk

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GCTOOLS class from file GCTOOLS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gctools import GCTOOLS
    return GCTOOLS(iface)
