# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AIGIS
                                 A QGIS plugin
 Modelos de inteligência artificial no Qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-06-11
        git sha              : $Format:%H$
        copyright            : (C) 2021 by MMS
        email                : mateusmelosiqueira@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import sys 
sys.path.append(os.path.join(os.path.dirname(__file__),'lib'))
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
#from PyQt5.QtCore import QVariant
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ai_gis_dialog import AIGISDialog
import os.path
from yolov5 import YOLOv5

#from sahi.model import Yolov5DetectionModel
from sahi import AutoDetectionModel
from sahi.utils.cv import read_image, visualize_object_predictions
from sahi.utils.file import download_from_url
from sahi.predict import get_prediction, get_sliced_prediction, predict


# from sahi.utils.cv import read_image
# from sahi.utils.file import download_from_url
# from sahi.predict import get_prediction, get_sliced_prediction, predict
# from IPython.display import Image
from PIL import Image
Image.MAX_IMAGE_PIXELS = 10000000000
#import yolov5
from osgeo import gdal
# import gdal
from qgis.core import *
from qgis.gui import *
from qgis.utils import *
from osgeo import osr
# import osr
import multiprocessing

class AIGIS:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'AIGIS_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&AI GIS')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('AIGIS', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/ai_gis/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'AIGIS'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&AI GIS'),
                action)
            self.iface.removeToolBarIcon(action)


    def inference(self):
        # set model params
        # model_path = "yolov5/weights/yolov5s.pt" # it automatically downloads yolov5s model to given path

        self.model_path = os.path.join(self.plugin_dir,'weights')
        print(self.model_path)
        self.device = "cpu"  # or "cpu"
        self.weight = None
        # init yolov5 model
        if(self.dlg.cb_tipo.currentText()=='Classes Gerais (COCO Dataset)'):
            self.weight = os.path.join(self.model_path,'yolov5x6.pt')
        elif(self.dlg.cb_tipo.currentText()=='Arvores_10cm'):
            self.weight = os.path.join(self.model_path,'arvores_mms_v1.pt')
        elif(self.dlg.cb_tipo.currentText()=='Arvores_1m'):
            self.weight = os.path.join(self.model_path,'arvores_mms_v2.pt')
        elif(self.dlg.cb_tipo.currentText()=='Lixao_24cm'):
            self.weight = os.path.join(self.model_path,'lixao_v1.pt')
        else:
            return#
        if (self.dlg.cb_slice_imagem.isChecked()):
            # detection_model = Yolov5DetectionModel(
                # model_path=self.weight,
                # prediction_score_threshold=float(self.dlg.cb_confidence.currentText()),
                # device="cpu",  # or 'cuda'
            # )
            detection_model = AutoDetectionModel.from_pretrained(
                model_type='yolov5',
                model_path=self.weight,
                confidence_threshold=float(self.dlg.cb_confidence.currentText()),
                device="cpu", # or 'cuda:0'
            )
            if (self.dlg.cb_size == '1280'):
                # results = self.yolov5.predict(self.img_dir, size=1280)
                self.img_size = 1280
            elif (self.dlg.cb_size == '640'):
                # results = self.yolov5.predict(self.img_dir, size=640)
                self.img_size = 1280
            else:
                # results = self.yolov5.predict(self.img_dir, size=640)
                self.img_size = 640

            if(self.file_folder_status==1):
                image = read_image(self.img_dir)

                result = get_sliced_prediction(
                    image,
                    detection_model,
                    slice_height=self.img_size,
                    slice_width=self.img_size,
                    overlap_height_ratio=float(self.dlg.cb_overlap.currentText()),
                    overlap_width_ratio=float(self.dlg.cb_overlap.currentText())
                )
                if (self.dlg.cb_mostrar_imagem.isChecked()):
                    visualization_result = visualize_object_predictions(
                        image,
                        object_prediction_list=result.object_prediction_list,
                        output_dir=os.path.join(self.plugin_dir, 'temp'),
                        file_name="temp_prediction",
                    )
                    # Image(os.path.join(self.plugin_dir,'temp','temp_prediction.png'))
                    img = Image.open(os.path.join(self.plugin_dir, 'temp', 'temp_prediction.png'))

                    img.show()
                i = 0
                if(self.dlg.cb_poligonos.isChecked()):
                    object_prediction_list = result.object_prediction_list
                    raster = gdal.Open(self.img_dir)
                    proj = osr.SpatialReference(wkt=raster.GetProjection())
                    epsg = int(proj.GetAttrValue('AUTHORITY', 1))
                    self.polygon = QgsVectorLayer('Polygon?crs=epsg:{}&index=yes'.format(epsg), 'torres_a', "memory")
                    self.point = QgsVectorLayer('Point?crs=epsg:{}&index=yes'.format(epsg), 'torres_p', "memory")
                    pr = self.polygon.dataProvider()
                    pr.addAttributes([QgsField("id", QVariant.Int), QgsField("classe",QVariant.String),QgsField("classe_id",QVariant.Int),QgsField("score",QVariant.Double)])
                    pr_p = self.point.dataProvider()
                    pr_p.addAttributes([QgsField("id", QVariant.Int), QgsField("classe",QVariant.String),QgsField("classe_id",QVariant.Int),QgsField("score",QVariant.Double)])
                    fields = self.polygon.fields()
                    self.polygon.updateFields()
                    self.polygon.commitChanges()
                    self.polygon.startEditing()
                    self.point.updateFields()
                    self.point.commitChanges()
                    self.point.startEditing()
                    for pred in object_prediction_list:
                        feat = QgsFeature()
                        feat.setFields(fields)
                        feat_p = QgsFeature()
                        feat_p.setFields(fields)
                        pred_coco = pred.to_coco_prediction().json
                        box = pred_coco['bbox']
                        classe = pred_coco['category_name']
                        classe_id = pred_coco['category_id']
                        score = round(pred.score.value,2)
                        feat.setAttributes([i,classe,classe_id,score])
                        feat_p.setAttributes([i, classe, classe_id, score])
                        xmin = box[0]
                        ymin = box[1]
                        xmax = xmin + box[2]
                        ymax = ymin + box[3]
                        x1,y1 = self.pixel2coord(self.img_dir,xmin,ymin)
                        x2,y2 = self.pixel2coord(self.img_dir,xmax,ymin)
                        x3,y3 = self.pixel2coord(self.img_dir,xmax,ymax)
                        x4,y4 = self.pixel2coord(self.img_dir,xmin,ymax)
                        #print(self.pixel2coord(self.img_dir,0,0))
                        geom = QgsGeometry.fromPolygonXY([[QgsPointXY(x1,y1),QgsPointXY(x2,y2),QgsPointXY(x3,y3),QgsPointXY(x4,y4)]])
                        geom_p = geom.centroid()
                        feat.setGeometry(geom)
                        feat_p.setGeometry(geom_p)
                        pr.addFeatures([feat])
                        pr_p.addFeatures([feat_p])
                        self.polygon.updateExtents()
                        self.point.updateExtents()
                        i = i + 1
                        #print(geom)
                    self.polygon.commitChanges()
                    self.point.commitChanges()
                    QgsProject.instance().addMapLayers([self.polygon])
                    if(self.dlg.cb_pontos.isChecked()):
                        QgsProject.instance().addMapLayers([self.point])
            elif(self.file_folder_status==0):
                images = [os.path.basename(x) for x in os.listdir(self.img_dir)]

                #@staticmethod
                def job(img):
                    print(os.path.join(self.img_dir, img))
                    image = read_image(os.path.join(self.img_dir,img))

                    result = get_sliced_prediction(
                        image,
                        detection_model,
                        slice_height=self.img_size,
                        slice_width=self.img_size,
                        overlap_height_ratio=float(self.dlg.cb_overlap.currentText()),
                        overlap_width_ratio=float(self.dlg.cb_overlap.currentText())
                    )
                    if(self.dlg.cb_mostrar_imagem.isChecked()):
                        visualization_result = visualize_object_predictions(
                            image,
                            object_prediction_list=result["object_prediction_list"],
                            output_dir=os.path.join(self.plugin_dir, 'temp'),
                            file_name=img,
                        )
                        # Image(os.path.join(self.plugin_dir,'temp','temp_prediction.png'))
                        img_ = Image.open(os.path.join(self.plugin_dir, 'temp', img)+'.png')
                        img_.show()

                process = []
                for img in images:
                    # p = multiprocessing.Process(target=worker, args=(img,))
                    # processes.append(p)
                    # p.start()
                    job(img)


                #
                # for process in processes:
                #     process.join()
                # if not hasattr(sys, 'argv'):
                #     sys.argv = ['']
                # pool = multiprocessing.Pool(2)
                # result_ = pool.map(func=job, iterable=images, chunksize=1)
                # pool.close()
                # pool.join()

                    i = 0
                    if (self.dlg.cb_poligonos.isChecked()):
                        object_prediction_list = result["object_prediction_list"]
                        raster = gdal.Open(self.img_dir)
                        proj = osr.SpatialReference(wkt=raster.GetProjection())
                        epsg = int(proj.GetAttrValue('AUTHORITY', 1))
                        self.polygon = QgsVectorLayer('Polygon?crs=epsg:{}&index=yes'.format(epsg), 'torres_a', "memory")
                        self.point = QgsVectorLayer('Point?crs=epsg:{}&index=yes'.format(epsg), 'torres_p', "memory")
                        pr = self.polygon.dataProvider()
                        pr.addAttributes([QgsField("id", QVariant.Int), QgsField("classe", QVariant.String),
                                          QgsField("classe_id", QVariant.Int), QgsField("score", QVariant.Double)])
                        pr_p = self.point.dataProvider()
                        pr_p.addAttributes([QgsField("id", QVariant.Int), QgsField("classe", QVariant.String),
                                            QgsField("classe_id", QVariant.Int), QgsField("score", QVariant.Double)])
                        fields = self.polygon.fields()
                        self.polygon.updateFields()
                        self.polygon.commitChanges()
                        self.polygon.startEditing()
                        self.point.updateFields()
                        self.point.commitChanges()
                        self.point.startEditing()
                        for pred in object_prediction_list:
                            feat = QgsFeature()
                            feat.setFields(fields)
                            feat_p = QgsFeature()
                            feat_p.setFields(fields)
                            pred_coco = pred.to_coco_prediction().json
                            box = pred_coco['bbox']
                            classe = pred_coco['category_name']
                            classe_id = pred_coco['category_id']
                            score = round(pred.score.value, 2)
                            feat.setAttributes([i, classe, classe_id, score])
                            feat_p.setAttributes([i, classe, classe_id, score])
                            xmin = box[0]
                            ymin = box[1]
                            xmax = xmin + box[2]
                            ymax = ymin + box[3]
                            x1, y1 = self.pixel2coord(self.img_dir, xmin, ymin)
                            x2, y2 = self.pixel2coord(self.img_dir, xmax, ymin)
                            x3, y3 = self.pixel2coord(self.img_dir, xmax, ymax)
                            x4, y4 = self.pixel2coord(self.img_dir, xmin, ymax)
                            # print(self.pixel2coord(self.img_dir,0,0))
                            geom = QgsGeometry.fromPolygonXY(
                                [[QgsPointXY(x1, y1), QgsPointXY(x2, y2), QgsPointXY(x3, y3), QgsPointXY(x4, y4)]])
                            geom_p = geom.centroid()
                            feat.setGeometry(geom)
                            feat_p.setGeometry(geom_p)
                            pr.addFeatures([feat])
                            pr_p.addFeatures([feat_p])
                            self.polygon.updateExtents()
                            self.point.updateExtents()
                            i = i + 1
                            # print(geom)
                        self.polygon.commitChanges()
                        self.point.commitChanges()
                        QgsProject.instance().addMapLayers([self.polygon])
                        if (self.dlg.cb_pontos.isChecked()):
                            QgsProject.instance().addMapLayers([self.point])
        else:
            self.yolov5 = YOLOv5(self.weight, self.device)

            if(self.file_folder_status==0):
                images = [os.path.basename(x) for x in os.listdir(self.img_dir)]
                for img in images:
                    if(self.dlg.cb_size == '1280'):
                        results = self.yolov5.predict(os.path.join(self.img_dir, img), size=1280)
                        self.img_size = 1280
                    elif (self.dlg.cb_size == '640'):
                        results = self.yolov5.predict(os.path.join(self.img_dir, img), size=640)
                        self.img_size = 1280
                    else:
                        results = self.yolov5.predict(os.path.join(self.img_dir, img), size=640)
                        self.img_size = 640
                    if (self.dlg.cb_mostrar_imagem.isChecked()):
                        results.show()
            elif(self.file_folder_status == 1):
                if(self.dlg.cb_size == '1280'):
                    results = self.yolov5.predict(self.img_dir, size=1280)
                    self.img_size = 1280
                elif(self.dlg.cb_size == '640'):
                    results = self.yolov5.predict(self.img_dir, size=640)
                    self.img_size = 1280
                else:
                    results = self.yolov5.predict(self.img_dir, size=640)
                    self.img_size = 640
                if(self.dlg.cb_mostrar_imagem.isChecked()):
                    results.show()


        # perform inference with larger input size
        #results = yolov5.predict(image1, size=1280)

        # perform inference with test time augmentation
        #results = yolov5.predict(image1, augment=True)

        # perform inference on multiple images
        #results = yolov5.predict([image1, image2], size=1280, augment=True)

        # show detection bounding boxes on image
        #results.show()

        # save results into "results/" folder
        #results.save(save_dir='results/')

    def pixel2coord(self,raster_path,x, y):
        raster = gdal.Open(raster_path)
        xoff, a, b, yoff, d, e = raster.GetGeoTransform()
        xp = a * x + b * y + a * 0.5 + b * 0.5 + xoff
        yp = d * x + e * y + d * 0.5 + e * 0.5 + yoff
        return xp, yp

    #def boxes2QgsPolygons(self,boxes):

    #def boxes2QgsPoints(self,boxes):

    def dir_file(self):
        self.file_folder_status = 1
        self.img_dir = QFileDialog.getOpenFileName()[0]
        self.dlg.line_file.setText(self.img_dir)
        print(self.img_dir)

    def dir_folder(self):
        self.file_folder_status = 0
        self.img_dir = QFileDialog.getExistingDirectory()
        self.dlg.line_file.setText(self.img_dir)

    def run(self):
        """Run method that performs all the real work"""
        self.plugin_dir = os.path.dirname(__file__)
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            #self.first_start = False
            self.dlg = AIGISDialog()
        self.dlg.pb_inference.clicked.connect(self.inference)
        self.dlg.pb_dir_file.clicked.connect(self.dir_file)
        self.dlg.pb_dir_folder.clicked.connect(self.dir_folder)
        self.dlg.cb_slice_imagem.setChecked(True)
        self.dlg.cb_mostrar_imagem.setChecked(True)
        self.dlg.cb_confidence.setCurrentText('0.80')
        self.file_folder_status = None
        # show the dialog
        self.dlg.show()
