# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AIINF
                                 A QGIS plugin
 Modelos de inteligência artificial no Qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-14
        git sha              : $Format:%H$
        copyright            : Mateus Melo Siqueira/Remis Balaniuk

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import sys 
sys.path.append(os.path.join(os.path.dirname(__file__),'lib'))

from .datagen_dialog import DATAGENDialog

from PIL import Image
Image.MAX_IMAGE_PIXELS = 10000000000
from qgis.core import QgsWkbTypes, QgsGeometry, QgsPoint, QgsProject, QgsMapLayerProxyModel
from qgis.core import *
from qgis.gui import *
from qgis.utils import *
from qgis.PyQt.QtWidgets import QMessageBox,QWidget, QAction, QFileDialog, QTableWidget, QTableWidgetItem, QGridLayout, QDialog, QPushButton, QProgressBar
from PyQt5.QtCore import QThread, pyqtSignal
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtWidgets import QToolButton, QMenu, QLineEdit, QLabel, QDialog, QPushButton, QCheckBox, QGridLayout
from qgis.PyQt.QtCore import QObject, Qt, QSize
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsWkbTypes, QgsGeometry, QgsPoint, QgsProject, QgsMapLayerProxyModel
from qgis.gui import QgsRubberBand, QgsMapLayerComboBox, QgsFieldComboBox
from PyQt5.QtWidgets import QTabWidget, QFrame,QAbstractItemView,  QMessageBox, QShortcut, QDockWidget, QComboBox, QLineEdit, QTableWidget, QTableWidgetItem, QCheckBox, QGridLayout, QLabel, QWidget, QSizePolicy,QSpacerItem, QPushButton
from qgis.PyQt.QtCore import Qt, QSize
from qgis.PyQt.QtGui import QColor, QCursor, QPixmap, QIcon, QImage
from PyQt5.QtCore import QThread, pyqtSignal
import processing
from qgis.core import QgsVectorLayer
from qgis.core import QgsVectorLayer,QgsRasterLayer, QgsRectangle, QgsVectorFileWriter, QgsGeometry,QgsFields, QgsField, QgsFeature, QgsProject
from qgis.PyQt.QtCore import QVariant
import processing
from qgis.core import *
from qgis.gui import *
from osgeo import gdal
from qgis.core import QgsProcessingFeatureSourceDefinition
from qgis.core import QgsProject, QgsVectorLayer, QgsRasterLayer, QgsCoordinateTransform, QgsCoordinateReferenceSystem, QgsFeatureRequest
from qgis.analysis import QgsRasterCalculatorEntry, QgsRasterCalculator
import random
import shutil


class WorkerGrade(QThread):
    def __init__(self, plugin_dir,cls_main):
        QThread.__init__(self)
        self.stp = False
        self.plugin_dir = plugin_dir
        self.datagen = cls_main


    up_list = pyqtSignal(list)
    results = pyqtSignal(list)

    def run(self):
        print("worker running!")




class WorkerClassify(QThread):
    def __init__(self, plugin_dir,cls_main):
        QThread.__init__(self)
        self.stp = False
        self.plugin_dir = plugin_dir
        self.datagen = cls_main


    up_list = pyqtSignal(list)
    results = pyqtSignal(list)

    def run(self):
        print("worker running!")

class WorkerTrain(QThread):
    def __init__(self, plugin_dir,cls_main):
        QThread.__init__(self)
        self.stp = False
        self.plugin_dir = plugin_dir
        self.datagen = cls_main


    up_list = pyqtSignal(list)
    results = pyqtSignal(list)

    def run(self):
        print("worker running!")


class MANCHAURBANA:
    def __init__(self, iface, cls_main):

        # Save reference to the QGIS interface
        self.gctools = cls_main
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = self.gctools.plugin_dir
        self.db = None
        self.savedirname = ''
        

    def setworker(self):

        self.worker_grade = WorkerGrade(self.plugin_dir,self)
        self.worker_grade.run()



    def CloseEvent(self, event):
        print("closed")


    def run(self):
        self.dlg = MANCHAURBANADialog()
        # show the dialog
        self.dlg.show()

        self.dlg.closeEvent = self.CloseEvent
